config/routes.rb
Gasored::Application.routes.draw do

  devise_for :users

  match 'gas_stations/index_app', :controller => 'gas_stations', :action => 'index_app'

  match 'gas_stations/detalles_gas/', :controller => 'gas_stations', :action => 'detalles_gas'

  resources :features

  resources :gas_stations

  root :to => 'gas_stations#index'

end

app/models/feature.rb
class Feature < ActiveRecord::Base
  attr_accessible :nombre
  has_and_belongs_to_many :gas_stations
end

app/models/gas_station.rb
class GasStation < ActiveRecord::Base
  attr_accessible :direccion, :foto1, :latitud, :longitud, :nombre, :telefono
  has_and_belongs_to_many :features
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
 
  before_filter :authenticate_user!
  
  # GET /features
  # GET /features.json
  def index
    @features = Feature.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @features }
    end
  end

  # GET /features/1
  # GET /features/1.json
  def show
    @feature = Feature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/new
  # GET /features/new.json
  def new
    @feature = Feature.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feature }
    end
  end

  # GET /features/1/edit
  def edit
    @feature = Feature.find(params[:id])
  end

  # POST /features
  # POST /features.json
  def create
    @feature = Feature.new(params[:feature])

    respond_to do |format|
      if @feature.save
        format.html { redirect_to @feature, notice: 'Feature was successfully created.' }
        format.json { render json: @feature, status: :created, location: @feature }
      else
        format.html { render action: "new" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /features/1
  # PUT /features/1.json
  def update
    @feature = Feature.find(params[:id])

    respond_to do |format|
      if @feature.update_attributes(params[:feature])
        format.html { redirect_to @feature, notice: 'Feature was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1
  # DELETE /features/1.json
  def destroy
    @feature = Feature.find(params[:id])
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/gas_stations_controller.rb
class GasStationsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /gas_stations
  # GET /gas_stations.json
  def index
    @gas_stations = GasStation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gas_stations, :include => :features }
    end
  end

  # GET /gas_stations/1
  # GET /gas_stations/1.json
  def show
    @gas_station = GasStation.find(params[:id])
    @features = @gas_station.features

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gas_station, :include => :features }
    end
  end

  # GET /gas_stations/new
  # GET /gas_stations/new.json
  def new
    @gas_station = GasStation.new

    @features = Feature.all
    @features_selected = []

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gas_station }
    end
  end

  # GET /gas_stations/1/edit
  def edit
    @gas_station = GasStation.find(params[:id])
    @features = Feature.all
    @features_selected = @gas_station.features
  end

  # POST /gas_stations
  # POST /gas_stations.json
  def create
    @gas_station = GasStation.new(params[:gas_station])

    #@features = Feature.find(params[:feature])
    if params["features"] != nil
      params["features"].each do |feature|
        f = Feature.find(feature)
        @gas_station.features << f
      end
    end

    respond_to do |format|
      if @gas_station.save
        format.html { redirect_to @gas_station, notice: 'Gas station was successfully created.' }
        format.json { render json: @gas_station, status: :created, location: @gas_station }
      else
        format.html { render action: "new" }
        format.json { render json: @gas_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gas_stations/1
  # PUT /gas_stations/1.json
  def update
    @gas_station = GasStation.find(params[:id])
    
    if not params["features"].blank?
      @gas_station.features.destroy_all

      params["features"].each do |feature|
        f = Feature.find(feature)
        @gas_station.features << f
      end
    else
      @gas_station.features.clear
    end

    respond_to do |format|
      if @gas_station.update_attributes(params[:gas_station])
        format.html { redirect_to @gas_station, notice: 'Gas station was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gas_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gas_stations/1
  # DELETE /gas_stations/1.json
  def destroy
    @gas_station = GasStation.find(params[:id])
    @gas_station.destroy

    respond_to do |format|
      format.html { redirect_to gas_stations_url }
      format.json { head :no_content }
    end
  end

  def index_app
    @gasos = GasStation.select("longitud, latitud, nombre, direccion")

    respond_to do |format|
      format.json { render json: @gasos } 
    end
  end

  def detalles_gas
    @gas_station = GasStation.find(params[:id])
    @simple_gas = GasStation.select("longitud, latitud, nombre, direccion")

    respond_to do |format|
      format.json { render json: @simple_gas }
    end
  end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/gas_stations_helper.rb
module GasStationsHelper
end

app/views/features/_form.html.erb
<%= simple_form_for(@feature, html: {class: "form-horizontal"}) do |f| %>
  <% if @feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feature.errors.count, "error") %> prohibited this feature from being saved:</h2>

      <ul>
      <% @feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.input :nombre %>
  </div>
  <div class="actions">
    <%= f.button :submit,  "Aceptar" %>
  </div>
<% end %>

app/views/features/edit.html.erb
<h1>Editar Característica</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @feature, :class => "btn btn-info" %> |
<%= link_to 'Regresar', features_path, :class => "btn btn-danger" %>

app/views/features/index.html.erb
<h1>Listado de Características</h1>

<%= link_to 'Añadir Nueva Característica', new_feature_path, :class => "btn btn-success" %>
<div class="container">
  <hr>
<% @features.each do |feature| %>
  <span>
    <p><strong>Nombre:</strong> <%= feature.nombre %></p>
    <p><%= link_to 'Mostrar', feature, :class => "btn btn-info" %> | <%= link_to 'Editar', edit_feature_path(feature), :class => "btn btn-warning" %> | <%= link_to 'Borrar', feature, method: :delete, data: { confirm: 'Estas Seguro?' }, :class => "btn btn-danger" %></p>
  </span>
  <hr>
<% end %>
</div>

app/views/features/new.html.erb
<h1>Nueva Característica</h1>

<%= render 'form' %>

<%= link_to 'Regresar', features_path, :class => "btn btn-danger" %>

app/views/features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @feature.nombre %>
</p>


<%= link_to 'Editar', edit_feature_path(@feature), :class => "btn btn-warning" %> |
<%= link_to 'Regresar', features_path, :class => "btn btn-danger" %>

app/views/gas_stations/_form.html.erb
<%= simple_form_for(@gas_station, html: {class: "form-horizontal"}) do |f| %>
  <% if @gas_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gas_station.errors.count, "error") %> prohibited this gas_station from being saved:</h2>

      <ul>
      <% @gas_station.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
  <div class="row-fluid">
    <div class="span6">
      <div class="field">
        <%= f.input :nombre %>
      </div>
      <div class="field">
        <%= f.input :direccion, :input_html => { :cols => 40, :rows => 6 } %>
      </div>
      <div class="field">
        <%= f.input :telefono %>
      </div>
      <div class="field">
        <%= f.input :latitud %>
      </div>
      <div class="field">
        <%= f.input :longitud %>
      </div>
      <div class="field">
        <%= f.input :foto1, label: 'Url de la foto' %>
      </div>
    </div>
    <div class="span6">
      <p><strong>Características:</strong></p>
      <% @features.each do |feature| %>
        <% flag = false %>
        <% @features_selected.each do |selected| %>
          <% if selected == feature %>
            <label>
              <%= check_box_tag 'features[]', feature.id, true %> <%= feature.nombre %>
            </label>
            <% flag = true %>
          <% end %>  
        <% end %>
        <% if flag == false%>
          <label>
            <%= check_box_tag 'features[]', feature.id, false %> <%= feature.nombre %>
          </label>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
  <div class="actions">
    <%= f.button :submit,  "Aceptar" %>
  </div>
  
<% end %>

app/views/gas_stations/edit.html.erb
<h1>Editar Gasolinera</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @gas_station, :class => "btn btn-info" %> |
<%= link_to 'Regresar', gas_stations_path, :class => "btn btn-danger" %>

app/views/gas_stations/index.html.erb
<h1>Listado de Gasolineras</h1>

<div class="container">
  <% if user_signed_in? %>
  <%= link_to 'Añadir nueva Gasolinera', new_gas_station_path, :class => "btn btn-success" %>
  <hr>
  <% end %>
  <% @gas_stations.each do |gas_station| %>
      <div class="container-fluid">
        <div class="row-fluid">
          <div class="span1">
            <p><%= link_to 'Mostrar', gas_station, :class => "btn btn-info" %></p>
          <% if user_signed_in? %>
            <p><%= link_to 'Editar', edit_gas_station_path(gas_station), :class => "btn btn-warning" %></p>
            <p><%= link_to 'Borrar', gas_station, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></p>
          <% end %>
          </div>
          <div class="span10">
            <span>
              <p><strong>Nombre</strong> <%= gas_station.nombre %></p>
              <p><strong>Direccion</strong> <%= gas_station.direccion %></p>
              <p><strong>Telefono</strong> <%= gas_station.telefono %></p>
              <p><strong>Latitud</strong> <%= gas_station.latitud %></p>
              <p><strong>Longitud</strong> <%= gas_station.longitud %></p>
              <p><strong>Foto</strong><br /><img class="foto-gas" src="<%= gas_station.foto1 %>" /></p>
            </span>
          </div>
        </div>
      </div>
    <hr>
  <% end %>
</div>

<br />

app/views/gas_stations/new.html.erb
<h1>Nueva Gasolinera</h1>

<%= render 'form' %>

<%= link_to 'Regresar', gas_stations_path, :class => "btn btn-danger" %>

app/views/gas_stations/show.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <%= link_to 'Añadir nueva Gasolinera', new_gas_station_path, :class => "btn btn-success" %>
  <hr>
<% end %>

<h3><%= @gas_station.nombre %></h3>


<p>
  <b>Direccion:</b>
  <%= @gas_station.direccion %>
</p>

<p>
  <b>Telefono:</b>
  <%= @gas_station.telefono %>
</p>

<p>
  <b>Latitud:</b>
  <%= @gas_station.latitud %>
</p>

<p>
  <b>Longitud:</b>
  <%= @gas_station.longitud %>
</p>

<p>
  <b>Url Foto:</b>
  <%= @gas_station.foto1 %>
  <br />
  <img class="foto-gas-min" src="<%= @gas_station.foto1 %>" />

</p>
<p><strong>Características:</strong></p>
<% if @features != [] %>
  <ul>
  <% @features.each do |feature| %>
   <li> <%= feature.nombre %> </li>
  <% end %>
<% else %>
  <p>No tiene características</p>
<% end %>

<% if user_signed_in? %>
<%= link_to 'Editar', edit_gas_station_path(@gas_station), :class => "btn btn-warnig" %> |<% end %>
<%= link_to 'Regresar', gas_stations_path, :class => "btn btn-danger" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gasored</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-fixed-top ">
		<div class="navbar-inner">
			<div class="container">
				<a class="brand" href="#">
					<img src="/assets/logo.png" width="150px">
				</a>
				<ul class="nav">
					<li>
						<%= link_to "Gasolineras", gas_stations_path %>
					</li>
					<li>
						<%= link_to "Características", features_path %>
					</li>
				</ul>
				<ul class="nav pull-right">
					<% if user_signed_in? %>
						<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
					<% else %>
						<li><%= link_to "Register", new_user_registration_path %></li>
						<li><%= link_to "Log in", new_user_session_path %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
	<div class="container">

		<%= yield %>
	
	</div>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	<footer class="navbar navbar-fixed-bottom">
		<div class="navbar-inner">
			<div class="container">
				<ul class="nav">
					<li>
						<p>GasoRed © 2013 Todos los derechos reserados.</p>
					</li>
				</ul>
				<ul class="pull-right">
					<li>
						<p>Sitio desarrollado por <a href="http://niumedia.mx">Niumedia</a></p>
					</li>
				</ul>
			</div>
		</div>
	</footer>
</body>
</html>